const fruitEmojis = {
  apple: "🍎",
  apricot: "🍑",
  avocado: "🥑",
  banana: "🍌",
  "bell pepper": "🫑",
  "black berry": "🫐",
  "black cherry": "🍒",
  "black currant": "🍇",
  blueberry: "🫐",
  cherry: "🍒",
  clementine: "🍊",
  cloudberry: "☁️",
  cranberry: "🍒",
  dragonfruit: "🐲",
  eggplant: "🍆",
  elderberry: "🫁",
  gooseberry: "🍇",
  kiwi: "🥝",
  lemon: "🍋",
  lime: "🍈",
  lingonberry: "🍓",
  mango: "🥭",
  nectarine: "🍑",
  olive: "🫒",
  orange: "🍊",
  papaya: "🧡",
  pea: "🥦",
  pear: "🍐",
  pineapple: "🍍",
  pomegranate: "🥭",
  raspberry: "🍇",
  strawberry: "🍓",
  tomato: "🍅",
  vanilla: "🍦",
  watermelon: "🍉",
  zucchini: "🥒",
}

export default fruitEmojis
